### ISSUE TITLE
Fold controls for case labels

### ISSUE THREAD

**Issue by cobra** [reapler/vscode-cfold#8]
Switch blocks with many cases and many statements per case label tend to get very large sometimes.
Folding individual case labels would help a lot getting a better overview, but at the moment neither vscode nor cfold provide fold controls for them.

**Comment by jpramosi** [comment]
Thank you for your feedback. This would be a neat feature.

**Comment by jpramosi** [comment]
ok.. I dare to say that if you got large case labels, their often enclosed with brackets {}. For small switches with not much content i rarely see this.
I assume it would be enough for you if only case labels with {} should have folding controls?
If not, no problem.

**Comment by cobra** [comment]
That was my first idea as a workaround, possibly even adding some. But sadly, this is not the case. The worst offender in this inherited mess of a legacy code base is a switch block spanning nearly 2000 lines, other places have triple-nested switch blocks, sometimes combined with large if/else blocks and many dozens of case labels at the second level. The authors successfully ignored any best practices and I have to reverse-engineer this spaghetti pile before refactoring.

**Comment by jpramosi** [comment]
I see, that sounds terrible. I will try to add fold controls for each case label (enclosed or not) in the following days.

**Comment by jpramosi** [comment]
Ok, i pushed a new version. 
You may activate this feature in Settings with `cfold.caseLabel.enable`
~However there's one restriction, 'cfold.withinFunction.enable' must be disabled.~
~I hope this doesn't bother you too much, but i think i will change this if i got more time in the future.~

Edit:
Limitation removed, since it doesn't made sense at all.
If there's something missing or doesn't work as expected, feel free to comment.

**Comment by cobra** [comment]
Looks good, thank you very much for the fast response!
There's only one problem: it doesn't work with tabs as indentation, only with spaces.

**Comment by jpramosi** [comment]
Strange that it doesn't work. To be honest i really never mind about tabs, since this style rather conflict with code hosting platforms like github and mess up the indention and most repositories seem to use space indention anyway.
I recommend to use formatting tools such as clang-format:

clang-format file:
```
SortIncludes: false
IndentWidth: 4
UseTab: Never
```
vscode settings:
```
Detect Indention: false
Insert Spaces: 4
Tab Size: 4
```

With a little bash script you can format all your files.

**Comment by cobra** [comment]
I'd prefer not discussing tabs-vs-spaces.

You're including spaces as word separators when searching for the switch and case keywords, which won't be matched with tabbed indentation. Additionally, the space between switch and the opening parenthesis is not strictly required.
I don't have a perfect solution for catching most legal cases at the moment.

**Comment by jpramosi** [comment]
I see, that makes sense.
If i got time, i will check this out https://github.com/reapler/vscode-cfold/issues/9.
